version: "3.8"

services:
  db:
    image: postgres:15
    container_name: bagofhoney-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: honey
      POSTGRES_PASSWORD: honey
      POSTGRES_DB: honey
    volumes:
      - db_data:/var/lib/postgresql/data
      # optional: initial scripts (wird nur beim ersten Start ausgeführt)
      - ./db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U honey -d honey"]
      interval: 5s
      timeout: 5s
      retries: 10

  honeypot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bagofhoney-app
    restart: unless-stopped
    # only for linux if you want it not bridged
    #network_mode: host
    depends_on:
      db:
        condition: service_healthy
    environment:
      HONEY_JDBC: jdbc:postgresql://db:5432/honey
      HONEY_DB_USER: honey
      HONEY_DB_PASS: honey
      SSH_PORT: "2222"
    ports:
      - "2222:2222/tcp"
      - "5000:5000/tcp"
      - "4000:4000/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:
