name: Build and Release JAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build JAR
        run: mvn -DskipTests package

      - name: Locate jar
        id: jar
        run: |
          FILE=$(ls target/*.jar | head -n 1)
          if [ -z "$FILE" ]; then
            echo "No jar found!" >&2
            exit 1
          fi
          echo "file=$FILE" >> $GITHUB_OUTPUT
          echo "Located: $FILE"

      - name: Create or update 'latest' release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "BagOfHoney (latest)"
          body: |
            🐝 **Automated release build**

            Commit: ${{ github.sha }}
            Triggered by: ${{ github.actor }}

            Includes all recent fixes and enhancements.
          files: |
            ${{ steps.jar.outputs.file }}#bagofhoney-latest.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
